### ISSUE TITLE
Haz este repo privado YA!!!

### ISSUE THREAD

**Issue by marvinjgh** [andreujuanc/actas-2024#6]
Estan dejando expuesta información sensible, que puede ser usada despues para usurpación de identidad, u otros actos delictivos.

**Comment by ipince** [comment]
Perdon, cual informacion es sensible?

**Comment by nucket** [comment]
Imagino se refiere a los ***Nombres Completos*** de los *Miembros de Mesa*, con su **Cedula de Identidad** y además de eso **La Firma**.

**Comment by marvinjgh** [comment]
Precisamente, la firma seria el elemento mas sensible, se podria argumentar tambien el dejar expuesto el api con el que se consulta la información de los votantes. Ya que permite automatizar la recopilación de datos de los votantes activos en los diversos centros.

**Comment by bkerz** [comment]
Pero estos mismos datos no son los que Maria Corina muestra en su web con las actas?

**Comment by bkerz** [comment]
@andreujuanc @ipince en cualquier caso, creo que se podrian solo tomar medidas para anonimizar los datos mas sensibles y dejar lo demas, que les parece la idea?

**Comment by ipince** [comment]
Pero los nombres completos ya son publicos.
Las firmas tambien son publicas (en las mismas actas en la pagina de MCM). Es mas, el CNE tambien tiene esas firmas digitalizadas, pues se hacen en la maquina, no en un papel.
Toda informacion de cedulas y nombres tambien es bastante publica. Hay muchas copias del registro electoral flotando por ahi en el internet. Me dices tu nombre, te doy tu cedula, eso no es secreto.

Me parece aqui no hay data que ya no sea publica y facilmente accesible por otros lados

**Comment by ipince** [comment]
Pero bueno, igual seria bueno anonimizar la data, pero creo que hay otras prioridades por encima, por lo menos por ahora
